### ISSUE TITLE
NORM function missing

### ISSUE THREAD

**Issue by dawsonphan** [lch14forever/BEEM#2]
I have a table of relative abundances formatted as instructed in the examples and by my browsing of all the functions only NORM can convert RA into biomass. However, when I try to search for the function NORM, it is missing. I was unable to find and install monomvn. Could this be the issue? I have all the pre-requisite packages other than monomvn.

**Comment by lch14forever** [comment]
Estimating the biomass is through the expectation optimisation process and `NORM` is not supposed to be called directly by the user (not an exported function). You need to call `beem:::NORM` in order to use it explicitly.

For `monomvn`, it is required by the Bayesian LASSO (not related to `NORM` though). It is on CRAN and you can directly install it.

**Comment by dawsonphan** [comment]
So if I use EM() it should in theory, automatically use NORM?

**Comment by lch14forever** [comment]
Yes.
